apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-cm
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;

    events {
      worker_connections  10240;
    }

    http {
      server {
        listen       80;
        server_name  localhost;
        location / {
          root   /www; #Change this line
          index  index.html index.htm;
        }

        location /coa/ {
            alias /data/;
            autoindex on;
            autoindex_format html;
        }
      }
    }
