apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-web-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html>
        <head>
            <title>Example</title>
        </head>
        <body>
            <a href="/coa/">[CoA]</a>
        </body>
    </html>
