apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-script-cm
data:
  run.bash: |
    #!/bin/sh

    # May change to rclone sync instead

    while :
    do
      # Use webmaster@napbiotec.io token to login 
      rclone copy GoogleDriveNAp: /data/napbiotec -vvv
      sleep 5m
    done
